
spring.application.name=codespark

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

cloud.aws.credentials.access-key=
cloud.aws.credentials.secret-key=
cloud.aws.region.static=ap-northeast-2
cloud.aws.s3.bucket=my-lecture-video
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.jpa.show-sql=true
spring.jpa.hibernate.use-new-id-generator-mappings=false
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.read-only=false
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.max-lifetime=240000
spring.datasource.hikari.max-pool-size=20

spring.messages.basename=messages
spring.messages.encoding=UTF-8